/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    IcCodeEditor: typeof import('./components/icCodeEditor/index.vue')['default']
    IcCodeHighlight: typeof import('./components/icCodeHighlight/index.vue')['default']
    IcFilter: typeof import('./components/icFilter/index.vue')['default']
    IconAdd: typeof import('./components/icon/iconAdd.vue')['default']
    IconArrows: typeof import('./components/icon/iconArrows.vue')['default']
    IconBbt: typeof import('./components/icon/iconBbt.vue')['default']
    IconCamel: typeof import('./components/icon/iconCamel.vue')['default']
    IconClear: typeof import('./components/icon/iconClear.vue')['default']
    IconCopy: typeof import('./components/icon/iconCopy.vue')['default']
    IconCopy2: typeof import('./components/icon/iconCopy2.vue')['default']
    IconDelete: typeof import('./components/icon/iconDelete.vue')['default']
    IconEdit: typeof import('./components/icon/iconEdit.vue')['default']
    IconExpand: typeof import('./components/icon/iconExpand.vue')['default']
    IconExport: typeof import('./components/icon/iconExport.vue')['default']
    IconFilter: typeof import('./components/icon/iconFilter.vue')['default']
    IconHome: typeof import('./components/icon/iconHome.vue')['default']
    IconKebab: typeof import('./components/icon/iconKebab.vue')['default']
    IconSave: typeof import('./components/icon/iconSave.vue')['default']
    IconSearch: typeof import('./components/icon/iconSearch.vue')['default']
    IconSetting: typeof import('./components/icon/iconSetting.vue')['default']
    IconSnake: typeof import('./components/icon/iconSnake.vue')['default']
    IcPage: typeof import('./components/icPage/index.vue')['default']
    IcUpload: typeof import('./components/icUpload/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
